### ISSUE TITLE
About MSC in regression.cpp

### ISSUE THREAD

**Issue by Theotaeho** [sandialabs/UQTk#11]
Hi, I am a new user of UQTk (Downloading github file Apr. 3, 2024).
I downloaded this in WSL2-Ubuntu 22.04

I sucessfully downloaded UQTk and binded UQTk with Python.
Every test was passed.

After making 'UQTk-install', I connected this to Jupyter lab.
The problem was that I got some errors for *.ipynb files in the folder, "examples/dfi_app/", especially in this part.
"subprocess.run(shlex.split(f"{path_to_python} {path_to_uq_pc} -r offline_post -p param_ranges.dat -m lsq -n {xs.shape[0]} -s rand -t 2 -z"), cwd=tmp, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)"
When I run this, the error message showed me that
"[Errno 2] No such file or directory: '/home/theokim/UQTk-install/examples/dfi_app/results.pk'"

When I visit the "uq_pc.py" file, the initial "pred_mode" was "ms".
Here, my problem can be solved after changing initial "pred_mode" from "ms" - mean + std to "m" - mean.

If I run "regression" using terminal using "ms" or "msc",
./regression -l0 -x /home/theokim/UQTk-install/examples/dfi_app/xdata.dat -y /home/theokim/UQTk-install/examples/dfi_app/ydata.dat -b PC -p /home/theokim/UQTk-install/examples/dfi_app/mi.dat -m ms
or
./regression -l0 -x /home/theokim/UQTk-install/examples/dfi_app/xdata.dat -y /home/theokim/UQTk-install/examples/dfi_app/ydata.dat -b PC -p /home/theokim/UQTk-install/examples/dfi_app/mi.dat -m msc

The terminal output was like below. And the results showed "Segmentation fault" in the code.:
############
xfile = /home/theokim/UQTk-install/examples/dfi_app/xdata.dat
yfile = /home/theokim/UQTk-install/examples/dfi_app/ydata.dat
basistype = PC
method = lsq
intpar = 5
dblpar = 0
strpar = LU
msc = msc
Dimensionality 3
Number of bases 56
Segmentation fault
############

If I run "regression" using terminal using "m",
############
xfile = /home/theokim/UQTk-install/examples/dfi_app/xdata.dat
yfile = /home/theokim/UQTk-install/examples/dfi_app/ydata.dat
basistype = PC
method = lsq
intpar = 5
dblpar = 0
strpar = LU
msc = m
Dimensionality 3
Number of bases 56
LOO error : 7.85189e-08
GCV error : -5.06816e-09
############

I think there are some problems inside of the source code when running the "ms" or "msc" options.
Can you fix it for this? If this is fixed, it would be much helpful for using this !

Thank you so much for your help!

Taeho Kim

**Comment by bjdebus** [comment]
Thanks @Theotaeho for reaching out. First of all, thanks for letting us know you installed UQTk in a WSL2-Ubuntu 22.04 environment. We have not yet tested this configuration, and it is good to know that you got it to work.

I followed your post and replicated the error on my installation. Let us look into it and see if we can fix it. I will let you know when we have a fix. 

Regards,
Bert

**Comment by Theotaeho** [comment]
Hi Bert, 

I tested other computers. Same errors occur too.
So I think there would be some errors in the "regression.cpp". 

Also, I found several issues in the latest version. 
I will let you know as soon as possible.

I think people will gradually more use same environment setting with me, so the correction of the code would be definitely helpful for other users! 

Best, 

Taeho Kim.

**Comment by bjdebus** [comment]
Much appreciated!

**Comment by bjdebus** [comment]
Hi @Theotaeho,

Thanks again for making us aware of this bug. We fixed it and I just pushed an update to github. If you pull the latest version, this tool should work again. Let us know if you run into any other problems.

Kind Regards,
Bert
