### ISSUE TITLE
Improve ImportError messages

### ISSUE THREAD

**Issue by padamson** [sandialabs/UQTk#2]
The import exception messages aren't always accurate. It would be better to have something like:

```python
try:
    from . import bcs
except ImportError as ie:
    print('PyUQTk SWIG bcs interface not imported.', ie)
```

**Comment by bjdebus** [comment]
Hi @padamson ,

Thanks again for your suggestion. We incorporated your recommendation in recent updates to the repo, and we will continue paying attention to this.
Thanks again for your contributions!
