### ISSUE TITLE
making examples compatible with Python3.x and recent numpy

### ISSUE THREAD

**Issue by padamson** [sandialabs/UQTk#4]
Would the UQTk team be open to a PR that makes the examples compatible with Python3.x and recent versions of numpy?

**Comment by l-boll** [comment]
Hi @padamson, 

Thank you for offering your support and our apologies for not getting back to you sooner.
We have pushed some recent updates. If the examples are still not compatible with Python3.x or recent versions of numpy we would appreciate any help or insight you wish to offer. Thank you for continuing to work with UQTk!
